version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
    volumes:
      - ./:/data/custom-nodes/n8n-nodes-masumi-payment:ro
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data: